# Generated by Django 2.2.5 on 2019-09-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('Bcode', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('Btitle', models.TextField(max_length=20)),
                ('Bauthor', models.TextField(max_length=20)),
                ('Bpublisher', models.TextField(max_length=20)),
            ],
        ),
    ]
